var PTS = {
kowalski:{
  name:"KOWALSKI,HAROLD J", dob:"Mar 14,1952", age:"72", sex:"MALE",
  mrn:"0042-8817", ward:"4-WEST RM 412", prov:"ANAND,PRIYA MD",
  workload:"4-WEST INPT Jun 20,26 09:30",
  banner:"Resuscitation Status: Full Code", cwad:"WAD",
  allergies:[
    {agent:"Penicillin",sev:"Severe",signs:"Anaphylaxis; Hives; Throat Swelling"},
    {agent:"Sulfonamides",sev:"Moderate",signs:"Rash; Urticaria"},
    {agent:"Iodinated Contrast",sev:"Mild",signs:"Flushing"},
  ],
  postings:["ALLERGIES","ADVANCE DIRECTIVE DISCUSSION (Mar 2025)","FALL RISK"],
  problems:[
    {s:"A",d:"Acute on chronic kidney disease (CKD 3b->4)",n:"eGFR 22 on admit",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Volume overload / decompensated HFrEF",n:"",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Heart failure w/ reduced EF (HFrEF)",n:"EF 35%",onset:"2019",upd:"06/18/2026",loc:"4-West Inpt"},
    {s:"A",d:"Type 2 diabetes mellitus",n:"HbA1c 9.1% poorly controlled",onset:"2005",upd:"06/18/2026",loc:"4-West Inpt"},
    {s:"A",d:"Hypertension",n:"On triple therapy",onset:"2001",upd:"06/18/2026",loc:"4-West Inpt"},
    {s:"A",d:"Hyperlipidemia",n:"",onset:"2003",upd:"2024",loc:"Primary Care"},
    {s:"A",d:"Peripheral artery disease (PAD)",n:"Claudication ~1.5 blocks",onset:"2017",upd:"2023",loc:"Vascular"},
    {s:"A",d:"Anemia of chronic kidney disease",n:"Baseline Hgb 9.8",onset:"2016",upd:"06/18/2026",loc:"4-West Inpt"},
    {s:"A",d:"Obstructive sleep apnea",n:"CPAP 10 cmH2O",onset:"2015",upd:"2024",loc:"Pulm Clinic"},
    {s:"A",d:"Gout",n:"On allopurinol, no flares x18 months",onset:"2011",upd:"2024",loc:"Primary Care"},
  ],
  meds_home:[
    {n:"FUROSEMIDE 40MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/10/2026",ref:"0",stat:"active"},
    {n:"CARVEDILOL 12.5MG TAB",sig:"TAKE ONE TAB PO BID",lf:"05/10/2026",ref:"2",stat:"active"},
    {n:"LISINOPRIL 10MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/10/2026",ref:"2",stat:"active"},
    {n:"AMLODIPINE 5MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/10/2026",ref:"2",stat:"active"},
    {n:"ATORVASTATIN 40MG TAB",sig:"TAKE ONE TAB PO AT BEDTIME",lf:"05/10/2026",ref:"5",stat:"active"},
    {n:"METFORMIN HCL 1000MG TAB",sig:"TAKE ONE TAB PO BID WITH FOOD",lf:"05/10/2026",ref:"3",stat:"active"},
    {n:"ALLOPURINOL 300MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/10/2026",ref:"3",stat:"active"},
    {n:"ASPIRIN 81MG TAB EC",sig:"TAKE ONE TAB PO EVERY MORNING",lf:"05/10/2026",ref:"11",stat:"active"},
    {n:"DARBEPOETIN ALFA 60MCG/ML INJ",sig:"INJECT 60MCG SC EVERY 2 WEEKS",lf:"06/01/2026",ref:"1",stat:"active"},
  ],
  meds_inpt:[
    {n:"FUROSEMIDE 80MG/ML INJ",sig:"Give: 80MG IVP Q12H",stop:"06/25/2026",stat:"active",ind:"FOR VOLUME OVERLOAD / DIURESIS"},
    {n:"CARVEDILOL 12.5MG TAB",sig:"Give: 12.5MG PO BID",stop:"",stat:"active",ind:"FOR HEART FAILURE"},
    {n:"LISINOPRIL 5MG TAB",sig:"Give: 5MG PO DAILY",stop:"",stat:"active",ind:"FOR HEART FAILURE [DOSE REDUCED FROM 10MG]"},
    {n:"AMLODIPINE 10MG TAB",sig:"Give: 10MG PO DAILY",stop:"",stat:"active",ind:"FOR HTN [UPTITRATED 06/20]"},
    {n:"ATORVASTATIN 40MG TAB",sig:"Give: 40MG PO QHS",stop:"",stat:"active",ind:"FOR HYPERLIPIDEMIA"},
    {n:"NPH INSULIN 10 UNITS",sig:"Give: 10 UNITS SC BID",stop:"",stat:"active",ind:"FOR DM2 INPATIENT"},
    {n:"INSULIN REGULAR SLIDING SCALE",sig:"Give: PER SCALE SC AC+HS",stop:"",stat:"active",ind:"FOR DM2"},
    {n:"ALLOPURINOL 100MG TAB",sig:"Give: 100MG PO DAILY",stop:"",stat:"active",ind:"FOR GOUT [RENAL DOSE]"},
    {n:"HEPARIN 5000 UNITS/ML INJ",sig:"Give: 5000 UNITS SC Q8H",stop:"",stat:"active",ind:"FOR DVT PROPHYLAXIS"},
    {n:"PANTOPRAZOLE 40MG INJ",sig:"Give: 40MG IVP DAILY",stop:"",stat:"active",ind:"FOR GI PROPHYLAXIS"},
    {n:"METFORMIN HCL 1000MG TAB",sig:"Give: HOLD",stop:"",stat:"HELD",ind:"FOR DM2 -- HELD FOR AKI"},
  ],
  notes:[
    {date:"Jun 20,26",title:"INTERNAL MEDICINE PROGRESS NOTE",loc:"4-West Inpt",auth:"TORRES,SAMUEL MD / ANAND,PRIYA MD",
     body:"LOCAL TITLE: INTERNAL MEDICINE PROGRESS NOTE\nSTANDARD TITLE: PHYSICIAN PROGRESS NOTE\nDATE OF NOTE: JUN 20, 2026@09:30       ENTRY DATE: JUN 20, 2026@09:45\nAUTHOR: TORRES,SAMUEL MD (PGY-2)       EXP COSIGNER: ANAND,PRIYA MD\nURGENCY:                               STATUS: COMPLETED\n\nSUBJECTIVE:\nPatient reports mild improvement in dyspnea. States he can lie flat\ntonight without as much difficulty. Leg swelling a tiny bit better.\nContinues fatigue. Denies chest pain, palpitations, fever, chills.\n\nOBJECTIVE:\nT 37.1C  HR 78  BP 148/88  RR 18  SpO2 94% on 2L NC\nWeight: 97.3 kg (admit wt 101.2 kg) -- net -3.9 kg\n\nGen: A&Ox3. Mildly dyspneic at rest.\nCV: RRR. S3 gallop present. JVD to jaw at 45 degrees.\nPulm: Bibasilar crackles, improved from admission.\nExt: 2+ pitting edema bilateral LE to mid-shin (improved from 3+).\n\nASSESSMENT & PLAN:\n1. DECOMPENSATED HFREF / VOLUME OVERLOAD\n   - Continue IV furosemide 80mg BID\n   - Daily weights, strict I&Os, fluid restriction 1.5L/day\n   - Goal net negative 1-1.5L/day\n2. ACUTE ON CHRONIC CKD (eGFR 22, baseline ~38)\n   - Cr 2.8 today (down from 3.1 admit). Nephrology following.\n3. T2DM -- POORLY CONTROLLED (HbA1c 9.1%)\n   - Metformin held (AKI); NPH 10u BID + sliding scale\n4. HYPERTENSION -- amlodipine uptitrated to 10mg today\n5. ANEMIA OF CKD -- Hgb 9.0; continue darbepoetin\n\nCODE STATUS: Full code (confirmed)\n\n/es/ TORRES,SAMUEL MD PGY-2\nSigned: 06/20/2026 09:45\nCosigned by: ANAND,PRIYA MD 06/20/2026 11:02"},
    {date:"Jun 20,26",title:"VAAES ACUTE INPATIENT NSG SHIFT ASSESSMENT",loc:"4-West Inpt",auth:"BREWSTER,SANDRA RN",
     body:"LOCAL TITLE: VAAES ACUTE INPATIENT NSG SHIFT ASSESSMENT\nDATE OF NOTE: JUN 20, 2026@07:10       STATUS: COMPLETED\nAUTHOR: BREWSTER,SANDRA RN\n\nNURSING ASSESSMENT 0700-0800:\nPatient alert and oriented x3. Cooperative. HOB 30 degrees.\nBilateral LE edema 2+ to mid-shin, improved. Pedal pulses 2+.\nO2: 2L NC. SpO2 94% at rest.\nFALL RISK: Morse score 45 (MODERATE). Bed alarm ON.\n\nMEDICATIONS 0600-0800:\n  Carvedilol 12.5mg PO .......... 06:15 given\n  NPH Insulin 10u SC ............ 07:00 given, left abdomen\n  FSBG 07:00: 174 mg/dL -- no correction needed\n\n/es/ BREWSTER,SANDRA RN\nSigned: 06/20/2026 07:22"},
    {date:"Jun 18,26",title:"HISTORY AND PHYSICAL",loc:"4-West Inpt",auth:"ANAND,PRIYA MD",
     body:"LOCAL TITLE: HISTORY AND PHYSICAL\nDATE OF NOTE: JUN 18, 2026@13:00       STATUS: COMPLETED\nAUTHOR: ANAND,PRIYA MD\n\nCHIEF COMPLAINT:\nMy legs are so swollen I can barely walk, and I cannot breathe when I lay down.\n\nHISTORY OF PRESENT ILLNESS:\nMr. Kowalski is a 72-year-old male with HFrEF (EF 35%), CKD 3b,\nT2DM, HTN, and PAD presenting with 10-day progressive bilateral\nLE edema and 5-day worsening dyspnea on exertion, now with\northopnea (3 pillows) and PND x2 nights.\n\nPHYSICAL EXAM:\nVitals: T 37.3C, HR 98, BP 162/96, RR 22, SpO2 91% RA\nWt: 101.2 kg\nCV: Tachycardic, S3 gallop. JVD to angle of jaw.\nPulm: Bibasilar crackles to mid-lung fields.\nExt: 3+ pitting edema bilateral LE to knees.\n\nASSESSMENT: Decompensated HFrEF. Admit for IV diuresis.\nCODE STATUS: Full code, confirmed.\n\n/es/ ANAND,PRIYA MD\nSigned: 06/18/2026 14:30"},
  ],
  consults:[
    {date:"Jun 19,26",stat:"dc",title:"NEPHROLOGY CONSULT",num:"9705111",
     body:"Jun 19,26   (dc)  NEPHROLOGY CONSULT  Cons #: 9705111\n\nTo Service:   NEPHROLOGY\nRequesting:   ANAND,PRIYA MD\nDiagnosis:    Acute on Chronic Kidney Disease (N18.4)\n\nASSESSMENT:\nAKI multifactorial: cardiorenal syndrome type 1 + pre-existing CKD.\n\nRECOMMENDATIONS:\n1. Continue diuresis cautiously. Accept Cr up to 3.3-3.5.\n2. Avoid full-dose ACEi until Cr trending down, K+ <5.0.\n3. Avoid nephrotoxins: NSAIDs, aminoglycosides, gadolinium.\n4. If Cr >3.5 or K+ >5.5 -- reassess for CRRT candidacy.\n5. Outpatient nephrology f/u within 2 weeks.\n\n/es/ KARIM,FATIMA MD\nSigned: 06/19/2026 17:15\nStatus: COMPLETE"},
    {date:"Jun 19,26",stat:"dc",title:"CARDIOLOGY CONSULT",num:"9705112",
     body:"Jun 19,26   (dc)  CARDIOLOGY CONSULT  Cons #: 9705112\n\nTo Service:   CARDIOLOGY\nDiagnosis:    Decompensated HFrEF (I50.20)\n\nASSESSMENT:\nDecompensated HFrEF from diuretic non-adherence. Troponin delta\nNEGATIVE -- not acute ischemia.\n\nRECOMMENDATIONS:\n1. Discharge on furosemide 60mg PO daily.\n2. Continue carvedilol. Do NOT hold.\n3. Add sacubitril/valsartan once AKI resolves, Cr <2.5.\n4. Cardiology clinic f/u within 2 weeks.\n\n/es/ NGUYEN,LINH MD\nSigned: 06/19/2026 17:00\nStatus: COMPLETE"},
  ],
  labs:[
    {name:"BASIC METABOLIC PANEL",cols:["06/18","06/19AM","06/19PM","06/20","Ref"],rows:[
      {t:"Sodium",v:["138","137","137","138","136-145"],f:["","","",""]},
      {t:"Potassium",v:["5.2","5.1","5.1","4.8","3.5-5.0"],f:["H","H","H",""]},
      {t:"CO2",v:["19","20","21","21","22-29"],f:["L","L","L","L"]},
      {t:"BUN",v:["58","52","50","48","7-20"],f:["H","H","H","H"]},
      {t:"Creatinine",v:["3.1","2.9","2.9","2.8","0.6-1.2"],f:["H","H","H","H"]},
      {t:"eGFR",v:["22","24","24","25",">60"],f:["L","L","L","L"]},
      {t:"Glucose",v:["218","196","188","174","70-100"],f:["H","H","H","H"]},
      {t:"Calcium",v:["8.1","8.0","8.1","8.2","8.5-10.2"],f:["L","L","L","L"]},
    ]},
    {name:"COMPLETE BLOOD COUNT",cols:["06/18","06/20","Ref"],rows:[
      {t:"WBC",v:["8.2","7.9","4.5-11.0"],f:["",""]},
      {t:"HGB",v:["9.2","9.0","13.5-17.5"],f:["L","L"]},
      {t:"HCT",v:["28.1","27.6","41-53"],f:["L","L"]},
      {t:"MCV",v:["81","82","80-100"],f:["",""]},
      {t:"PLT",v:["214","208","150-400"],f:["",""]},
    ]},
    {name:"CARDIAC / SPECIAL LABS",cols:["Value","Date","Ref"],rows:[
      {t:"BNP",v:["1840 pg/mL","06/18","<100"],f:["H"]},
      {t:"Troponin I (hs)",v:["0.062 ng/mL","06/18","<0.04"],f:["H"]},
      {t:"HbA1c",v:["9.1%","06/18","<5.7%"],f:["H"]},
      {t:"Albumin",v:["3.1 g/dL","06/18","3.5-5.0"],f:["L"]},
    ]},
    {name:"URINALYSIS (06/18)",cols:["Result","Reference"],rows:[
      {t:"Protein",v:["3+ (780 mg/dL)","Negative"],f:["H"]},
      {t:"Glucose",v:["2+","Negative"],f:["H"]},
      {t:"Blood",v:["1+","Negative"],f:["H"]},
      {t:"Casts",v:["GRANULAR CASTS PRESENT","None"],f:["H"]},
    ]},
  ],
  vitals:[
    {dt:"06/20 06:00",t:"37.1",hr:"78",bp:"148/88",rr:"18",spo2:"94% 2L NC",wt:"97.3",ht:"",pn:"0",pox:"94",qual:""},
    {dt:"06/19 18:00",t:"36.9",hr:"80",bp:"149/88",rr:"18",spo2:"95% 2L NC",wt:"--",ht:"",pn:"0",pox:"95",qual:""},
    {dt:"06/19 06:00",t:"37.0",hr:"82",bp:"150/90",rr:"19",spo2:"94% 2L NC",wt:"99.1",ht:"",pn:"0",pox:"94",qual:""},
    {dt:"06/18 18:00",t:"37.1 H",hr:"88",bp:"154/92 H",rr:"20",spo2:"92% 2L L",wt:"--",ht:"",pn:"0",pox:"92",qual:""},
    {dt:"06/18 11:50",t:"37.3 H",hr:"98 H",bp:"162/96 H",rr:"22 H",spo2:"91% RA L",wt:"101.2",ht:"69 in",pn:"2",pox:"91",qual:"SITTING"},
  ],
  io:[
    {dt:"06/20 (to 07:00)",po:"250",iv:"0",uo:"480",net:"-230"},
    {dt:"06/19",po:"900",iv:"200",uo:"2800",net:"-1700"},
    {dt:"06/18",po:"800",iv:"400",uo:"900",net:"+300 H"},
  ],
  imaging:[
    {date:"06/18/2026 12:14",name:"CHEST XRAY 2 VIEWS",stat:"Verified",examstat:"Complete",cnum:"2287",
     body:"CHEST X-RAY PA AND LATERAL\nExam: JUN 18, 2026@12:14   Req: ANAND,PRIYA MD\n\nFINDINGS:\nCardiomegaly (CTR ~0.62). Bilateral pulmonary vascular congestion\nwith upper lobe diversion. Interstitial edema with Kerley B lines\nat bilateral bases. Small bilateral pleural effusions.\n\nIMPRESSION:\n1. Moderate pulmonary edema and cardiomegaly consistent with\n   decompensated heart failure.\n2. Small bilateral pleural effusions.\n\n/ES/GREENBERG,ALAN MD"},
    {date:"06/18/2026 15:30",name:"ULTRASOUND RENAL BILATERAL",stat:"Verified",examstat:"Complete",cnum:"2288",
     body:"RENAL ULTRASOUND BILATERAL\nExam: JUN 18, 2026@15:30   Req: ANAND,PRIYA MD\n\nFINDINGS:\nRight kidney: 9.8 cm. Increased cortical echogenicity.\nLeft kidney: 9.6 cm. Similar appearance. No hydronephrosis.\n\nIMPRESSION:\n1. Bilateral echogenic kidneys with cortical thinning consistent\n   with chronic parenchymal renal disease.\n2. No obstructive uropathy.\n\n/ES/GREENBERG,ALAN MD"},
  ],
  orders:[
    {svc:"Life-Sustaining Treat",ord:">> Full Code -- Resuscitate with all available means.\n   Confirmed with patient and family 06/18/2026.",start:"06/18/26 14:30",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Nursing",ord:"DAILY WEIGHT\n  Indication: Heart failure monitoring",start:"06/18/26 14:40",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Nursing",ord:"STRICT INTAKE AND OUTPUT\n  Foley catheter in place",start:"06/18/26 14:40",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Nursing",ord:"O2: TITRATE TO SpO2 >92% via NC",start:"06/18/26 14:45",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Diet",ord:"DIET: 2GM SODIUM / 2L FLUID RESTRICTION",start:"06/18/26 14:45",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"BMP (BASIC METABOLIC PANEL) DAILY\n  Collection: 06:00  Indication: AKI monitoring",start:"06/18/26 15:00",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"FSBG QID AC + HS\n  Indication: DM2 glycemic management",start:"06/18/26 15:00",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Consult",ord:"NEPHROLOGY CONSULT [COMPLETED]\n  Indication: Acute on CKD, proteinuria",start:"06/18/26 15:10",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Consult",ord:"CARDIOLOGY CONSULT [COMPLETED]\n  Indication: Decompensated HFrEF",start:"06/18/26 15:10",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Radiology",ord:"RENAL ULTRASOUND BILATERAL [COMPLETED]",start:"06/18/26 15:15",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
  ],
  appointments:[
    {dt:"06/18/2026 11:42",loc:"4-West Inpatient",action:"Admitted"},
    {dt:"06/15/2026 14:00",loc:"Primary Care Clinic",action:"Checked Out"},
  ],
  immunizations:[
    {name:"COVID-19 (PFIZER) MRNA",reaction:"No reaction",dt:"Dec 30, 2024"},
    {name:"INFLUENZA SEASONAL",reaction:"No reaction",dt:"Oct 15, 2024"},
    {name:"PNEUMOCOCCAL (PPSV23)",reaction:"No reaction",dt:"Sep 02, 2022"},
  ],
},
chen:{
  name:"CHEN,MARGARET L", dob:"Sep 02,1967", age:"58", sex:"FEMALE",
  mrn:"0059-2241", ward:"4-WEST RM 408", prov:"ANAND,PRIYA MD",
  workload:"4-WEST INPT Jun 20,26 10:00",
  banner:"Resuscitation Status: Full Code", cwad:"WA",
  allergies:[
    {agent:"Penicillin",sev:"Severe",signs:"Anaphylaxis; Throat Swelling; Urticaria"},
    {agent:"Codeine",sev:"Moderate",signs:"Nausea; Vomiting"},
  ],
  postings:["ALLERGIES","TOBACCO CESSATION COUNSELING OFFERED"],
  problems:[
    {s:"A",d:"Acute COPD exacerbation",n:"Moderate-severe, GOLD III baseline",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Community-acquired pneumonia (RLL)",n:"Pneumococcal Ag positive",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Hypercapnic respiratory failure",n:"PaCO2 54, pH 7.32 on admission",onset:"06/2026",upd:"06/19/2026",loc:"4-West Inpt"},
    {s:"A",d:"COPD (SCT 13645005)",n:"GOLD III, FEV1 44% predicted",onset:"2014",upd:"06/19/2026",loc:"4-West Inpt"},
    {s:"A",d:"Hypertension",n:"",onset:"2010",upd:"2025",loc:"Primary Care"},
    {s:"A",d:"GERD",n:"",onset:"2012",upd:"2024",loc:"Primary Care"},
    {s:"A",d:"Osteoporosis",n:"On bisphosphonate therapy",onset:"2018",upd:"2024",loc:"Primary Care"},
    {s:"A",d:"Major depression",n:"Stable on SSRI",onset:"2020",upd:"2025",loc:"Behavioral Health"},
    {s:"A",d:"Tobacco use disorder",n:"Active, ~10 cig/day, 40 pack-yr",onset:"ongoing",upd:"06/19/2026",loc:"4-West Inpt"},
  ],
  meds_home:[
    {n:"TIOTROPIUM (SPIRIVA) 18MCG INHL",sig:"INHALE 1 CAPSULE DAILY VIA HANDIHALER",lf:"05/15/2026",ref:"2",stat:"active"},
    {n:"FLUTICASONE/SALMETEROL (ADVAIR 250/50) INHL",sig:"INHALE 1 PUFF BID",lf:"05/15/2026",ref:"2",stat:"active"},
    {n:"ALBUTEROL HFA 90MCG INHL (RESCUE)",sig:"INHALE 2 PUFFS Q4-6H PRN SOB",lf:"05/15/2026",ref:"5",stat:"active"},
    {n:"AMLODIPINE 5MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/15/2026",ref:"3",stat:"active"},
    {n:"LISINOPRIL 10MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/15/2026",ref:"3",stat:"active"},
    {n:"OMEPRAZOLE 20MG CAP",sig:"TAKE ONE CAP PO DAILY BEFORE MEALS",lf:"05/15/2026",ref:"5",stat:"active"},
    {n:"SERTRALINE 50MG TAB",sig:"TAKE ONE TAB PO DAILY",lf:"05/15/2026",ref:"3",stat:"active"},
    {n:"ALENDRONATE 70MG TAB",sig:"TAKE ONE TAB PO ONCE WEEKLY ON EMPTY STOMACH",lf:"05/01/2026",ref:"3",stat:"active"},
  ],
  meds_inpt:[
    {n:"AZITHROMYCIN 500MG/250ML INJ",sig:"Give: 500MG IVPB DAILY",stop:"06/24/2026",stat:"active",ind:"FOR CAP -- PCN ALLERGIC"},
    {n:"CEFTRIAXONE 1GM INJ",sig:"Give: 1GM IV Q24H",stop:"06/24/2026",stat:"active",ind:"FOR CAP -- DUAL COVERAGE"},
    {n:"METHYLPREDNISOLONE 40MG INJ",sig:"Give: 40MG IVP Q12H",stop:"06/23/2026",stat:"active",ind:"FOR COPD EXACERBATION"},
    {n:"ALBUTEROL/IPRATROPIUM NEB",sig:"Give: UNIT DOSE NEB Q4H + PRN",stop:"",stat:"active",ind:"FOR BRONCHODILATION"},
    {n:"AMLODIPINE 5MG TAB",sig:"Give: 5MG PO DAILY",stop:"",stat:"active",ind:"FOR HYPERTENSION"},
    {n:"OMEPRAZOLE 20MG CAP",sig:"Give: 20MG PO DAILY",stop:"",stat:"active",ind:"FOR GERD"},
    {n:"SERTRALINE 50MG TAB",sig:"Give: 50MG PO DAILY",stop:"",stat:"active",ind:"FOR DEPRESSION"},
    {n:"ENOXAPARIN 40MG/0.4ML INJ",sig:"Give: 40MG SC DAILY",stop:"",stat:"active",ind:"FOR DVT PROPHYLAXIS"},
    {n:"LISINOPRIL 10MG TAB",sig:"Give: HOLD",stop:"",stat:"HELD",ind:"FOR HTN -- HELD (RESPIRATORY CONCERN)"},
    {n:"ALENDRONATE 70MG TAB",sig:"Give: HOLD",stop:"",stat:"HELD",ind:"FOR OSTEOPOROSIS -- HELD (NPO CONCERN)"},
  ],
  notes:[
    {date:"Jun 20,26",title:"INTERNAL MEDICINE PROGRESS NOTE",loc:"4-West Inpt",auth:"TORRES,SAMUEL MD / ANAND,PRIYA MD",
     body:"LOCAL TITLE: INTERNAL MEDICINE PROGRESS NOTE\nDATE OF NOTE: JUN 20, 2026@10:00       STATUS: COMPLETED\nAUTHOR: TORRES,SAMUEL MD (PGY-2)       EXP COSIGNER: ANAND,PRIYA MD\n\nSUBJECTIVE:\nMs. Chen slightly improved since admission. Still very SOB with\nspeaking but nebulizer treatments are helping. Cough productive\nof thick yellow-green sputum. No hemoptysis.\n\nOBJECTIVE:\nT 38.2C  HR 104  BP 136/84  RR 26 H  SpO2 93% on 4L NC\nGen: Moderate respiratory distress. Accessory muscles. Tripod.\nPulm: Diffuse expiratory wheezing. Decreased BS right base.\n\nASSESSMENT & PLAN:\n1. COPD EXACERBATION -- Nebs q4h; Methylprednisolone 40mg IV q12h\n   TARGET SpO2 88-92% -- avoid over-oxygenation\n2. CAP RLL -- Azithromycin 500mg IV + ceftriaxone 1g IV q24h\n3. HYPERCAPNIC RF -- trend ABGs; BiPAP if pH <7.25\n4. HTN -- amlodipine continued; lisinopril HELD\n\nCODE STATUS: Full code\n\n/es/ TORRES,SAMUEL MD PGY-2\nSigned: 06/20/2026 10:20"},
    {date:"Jun 19,26",title:"HISTORY AND PHYSICAL",loc:"4-West Inpt",auth:"GOLDSTEIN,RACHEL MD (ED)",
     body:"LOCAL TITLE: HISTORY AND PHYSICAL\nDATE: JUN 19, 2026@03:50       STATUS: COMPLETED\nAUTHOR: GOLDSTEIN,RACHEL MD (EM)\n\nCHIEF COMPLAINT:\nI woke up and I could not breathe at all.\n\nHPI:\n58 yo F with COPD GOLD III, HTN, GERD presenting with acute\ndyspnea. 3-4 day prodrome of fever, productive cough, worsening DOE.\nCurrent smoker, 40 pack-years. Two prior COPD hospitalizations.\n\nPHYSICAL EXAM:\nVitals: T 38.4C, HR 112, BP 142/88, RR 28, SpO2 88% RA\nPulm: Diffuse expiratory wheeze. Decreased BS RLL.\nABG (RA): pH 7.32, PaO2 54, PaCO2 54, HCO3 30\n\nASSESSMENT: Acute COPD exacerbation (severe) + CAP (RLL) +\nhypercapnic respiratory failure. Admit.\n\n/es/ GOLDSTEIN,RACHEL MD\nSigned: 06/19/2026 05:30"},
  ],
  consults:[
    {date:"Jun 19,26",stat:"dc",title:"PULMONOLOGY CONSULT",num:"9705220",
     body:"Jun 19,26   (dc)  PULMONOLOGY CONSULT  Cons #: 9705220\n\nTo Service:   PULMONOLOGY\nDiagnosis:    COPD Exacerbation + Hypercapnic Respiratory Failure\n\nASSESSMENT:\nModerate-severe COPD exacerbation precipitated by pneumococcal\npneumonia. Acute-on-chronic hypercapnic respiratory failure.\n\nRECOMMENDATIONS:\n1. TARGET SpO2 88-92% STRICTLY. Avoid hyperoxia.\n2. BiPAP (IPAP 12/EPAP 5) if PaCO2 rises or pH <7.25.\n3. Repeat ABG in 12 hours.\n4. Smoking cessation: re-approach daily.\n\n/es/ WATTS,AISHA MD\nSigned: 06/19/2026 19:00\nStatus: COMPLETE"},
  ],
  labs:[
    {name:"COMPLETE BLOOD COUNT",cols:["06/19","06/20","Ref"],rows:[
      {t:"WBC",v:["14.2","13.8","4.5-11.0"],f:["H","H"]},
      {t:"Neutrophils",v:["88%","86%","50-70%"],f:["H","H"]},
      {t:"HGB",v:["12.8","12.6","12.0-16.0"],f:["",""]},
      {t:"PLT",v:["318","322","150-400"],f:["",""]},
    ]},
    {name:"BASIC METABOLIC PANEL",cols:["06/19","06/20","Ref"],rows:[
      {t:"Sodium",v:["140","139","136-145"],f:["",""]},
      {t:"Potassium",v:["3.3","3.4","3.5-5.0"],f:["L","L"]},
      {t:"CO2",v:["30","29","22-29"],f:["H","H"]},
      {t:"Creatinine",v:["0.9","0.8","0.5-1.1"],f:["",""]},
      {t:"Glucose",v:["148","136","70-100"],f:["H","H"]},
    ]},
    {name:"ARTERIAL BLOOD GAS (06/19 RA)",cols:["Value","Reference"],rows:[
      {t:"pH",v:["7.32","7.35-7.45"],f:["L"]},
      {t:"PaO2",v:["54 mmHg","75-100 mmHg"],f:["L"]},
      {t:"PaCO2",v:["54 mmHg","35-45 mmHg"],f:["H"]},
      {t:"HCO3",v:["30 mEq/L","22-26 mEq/L"],f:["H"]},
    ]},
    {name:"INFECTIOUS MARKERS",cols:["Value","Date","Ref"],rows:[
      {t:"CRP",v:["88 mg/L","06/19","<10 mg/L"],f:["H"]},
      {t:"Procalcitonin",v:["1.8 ng/mL","06/19","<0.25 ng/mL"],f:["H"]},
      {t:"Urine Pneumococcal Ag",v:["POSITIVE ***","06/19","Negative"],f:["H"]},
      {t:"Blood Culture x2",v:["PENDING","06/19","No growth"],f:[""]},
    ]},
  ],
  vitals:[
    {dt:"06/20 06:00",t:"38.2 H",hr:"104 H",bp:"136/84 H",rr:"26 H",spo2:"93% 4L",wt:"64",ht:"",pn:"0",pox:"93",qual:"SITTING"},
    {dt:"06/19 18:00",t:"37.8 H",hr:"100 H",bp:"134/82 H",rr:"22 H",spo2:"93% 4L",wt:"--",ht:"",pn:"0",pox:"93",qual:""},
    {dt:"06/19 03:50",t:"38.4 H",hr:"112 H",bp:"142/88 H",rr:"28 H",spo2:"88% RA L",wt:"64",ht:"67 in",pn:"3",pox:"88",qual:""},
  ],
  io:[
    {dt:"06/20 (to 07:00)",po:"200",iv:"100",uo:"310",net:"-10"},
    {dt:"06/19",po:"400",iv:"350",uo:"820",net:"-70"},
  ],
  imaging:[
    {date:"06/19/2026 04:20",name:"CHEST XRAY PA VIEW",stat:"Verified",examstat:"Complete",cnum:"2289",
     body:"CHEST X-RAY PA VIEW\nExam: JUN 19, 2026@04:20   Req: GOLDSTEIN,RACHEL MD (ED)\n\nFINDINGS:\nHyperinflated lungs with flattened diaphragms consistent with\nCOPD. Right lower lobe opacity with air bronchograms.\n\nIMPRESSION:\n1. Right lower lobe consolidation consistent with pneumonia.\n2. Hyperinflation consistent with chronic obstructive disease.\n\n/ES/GREENBERG,ALAN MD"},
  ],
  orders:[
    {svc:"Nursing",ord:"TARGET SpO2 88-92%\n  COPD patient -- avoid hyperoxia.",start:"06/19/26 05:45",prov:"GOLDSTEIN,RACHEL MD",stat:"active",loc:"1no"},
    {svc:"Nursing",ord:"FALL PRECAUTIONS -- Morse 35 (MODERATE)",start:"06/19/26 06:00",prov:"GOLDSTEIN,RACHEL MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"ABG Q12H while on supplemental O2",start:"06/19/26 06:00",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"CBC, BMP DAILY  Collection: 06:00",start:"06/19/26 06:00",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
    {svc:"Consult",ord:"PULMONOLOGY CONSULT [COMPLETED]",start:"06/19/26 08:00",prov:"ANAND,PRIYA MD",stat:"active",loc:"1no"},
  ],
  appointments:[
    {dt:"06/19/2026 03:50",loc:"4-West Inpatient (ED admit)",action:"Admitted"},
    {dt:"04/10/2026 09:00",loc:"Pulmonary Clinic",action:"Checked Out"},
  ],
  immunizations:[
    {name:"INFLUENZA SEASONAL",reaction:"No reaction",dt:"Oct 10, 2024"},
    {name:"COVID-19 (PFIZER) MRNA",reaction:"No reaction",dt:"Dec 15, 2024"},
  ],
},
okafor:{
  name:"OKAFOR,EMMANUEL C", dob:"Feb 27,1981", age:"45", sex:"MALE",
  mrn:"0071-5530", ward:"4-WEST RM 415", prov:"ANAND,PRIYA MD",
  workload:"4-WEST INPT Jun 20,26 10:30",
  banner:"Resuscitation Status: Full Code", cwad:"",
  allergies:[],
  postings:["NO KNOWN DRUG ALLERGIES (NKDA)"],
  problems:[
    {s:"A",d:"Diabetic ketoacidosis (SCT 420422005)",n:"Resolving; anion gap closed 06/20",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Type 1 diabetes mellitus (SCT 46635009)",n:"New-onset; GAD-65 Ab positive",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
    {s:"A",d:"Hypertriglyceridemia",n:"TG 284 mg/dL",onset:"06/2026",upd:"06/20/2026",loc:"4-West Inpt"},
  ],
  meds_home:[],
  meds_inpt:[
    {n:"INSULIN GLARGINE (LANTUS) 100U/ML INJ",sig:"Give: 20 UNITS SC AT BEDTIME",stop:"",stat:"active",ind:"FOR T1DM BASAL [STARTED 06/20 AFTER DRIP D/C]"},
    {n:"INSULIN LISPRO (HUMALOG) 100U/ML INJ",sig:"Give: PER CHO RATIO (1:15) SC WITH MEALS + CORRECTION",stop:"",stat:"active",ind:"FOR T1DM BOLUS INSULIN"},
    {n:"DEXTROSE 5% IN 0.45% NACL 1000ML",sig:"Give: IVPB AT ORDERED RATE",stop:"",stat:"active",ind:"FOR GLUCOSE MANAGEMENT"},
    {n:"ONDANSETRON 4MG/2ML INJ",sig:"Give: 4MG IV Q6H PRN NAUSEA",stop:"",stat:"active",ind:"FOR NAUSEA PRN"},
    {n:"INSULIN REGULAR IV DRIP",sig:"Give: PER DKA PROTOCOL IV CONTINUOUS",stop:"06/20/26 06:30",stat:"DISCONTINUED",ind:"FOR DKA -- D/C WHEN AG CLOSED"},
  ],
  notes:[
    {date:"Jun 20,26",title:"INTERNAL MEDICINE / ENDOCRINOLOGY PROGRESS NOTE",loc:"4-West Inpt",auth:"TORRES,SAMUEL MD + PATEL,TARIQ MD (ENDO)",
     body:"LOCAL TITLE: INTERNAL MEDICINE / ENDOCRINOLOGY PROGRESS NOTE\nDATE: JUN 20, 2026@10:30       STATUS: COMPLETED\nAUTHOR: TORRES,SAMUEL MD (PGY-2) / PATEL,TARIQ MD (ENDO)\n\nSUBJECTIVE:\nMr. Okafor: nausea and abdominal pain resolved. Tolerating PO.\nVery engaged; wife present.\n\nLABS 06/20:\n  Glucose 142  Na 138  K 4.1  Bicarb 22\n  ANION GAP: 11 (CLOSED -- was 24 on admit)\n\nASSESSMENT & PLAN:\n1. DKA -- RESOLVING. IV insulin drip D/C 06:30.\n2. NEW-ONSET T1DM\n   GAD-65 Ab POSITIVE (148 IU/mL); C-peptide 0.2 ng/mL\n   *** DO NOT USE: metformin, sulfonylureas, SGLT2 inhibitors ***\n3. DISCHARGE TARGET: 06/21\n\n/es/ TORRES,SAMUEL MD PGY-2\nSigned: 06/20/2026 10:55"},
    {date:"Jun 19,26",title:"HISTORY AND PHYSICAL",loc:"1no Workload",auth:"SULLIVAN,MICHAEL MD (ED)",
     body:"LOCAL TITLE: HISTORY AND PHYSICAL\nDATE: JUN 19, 2026@17:10       STATUS: COMPLETED\nAUTHOR: SULLIVAN,MICHAEL MD (EM)\n\nCHIEF COMPLAINT:\nI have been so thirsty, peeing constantly, and now I feel like I am going to pass out.\n\nHPI:\n45 yo M with NO prior medical history presenting with 3-week\nhistory of polyuria, polydipsia, weight loss (~8 lbs), fatigue.\nPast 48 hours: nausea, abdominal cramping. NKDA.\n\nPHYSICAL EXAM:\nVitals: T 37.4C, HR 112, BP 122/78, RR 24, SpO2 97% RA\nGen: Ill-appearing. KUSSMAUL RESPIRATIONS. Fruity breath.\nHEENT: Dry MM. Sunken eyes.\n\nLABS: Glucose 642, AG 24, pH 7.18, HCO3 8, PaCO2 22\n\nASSESSMENT:\n1. Diabetic ketoacidosis (DKA) -- severe\n2. New-onset diabetes (likely T1 given presentation)\n\n/es/ SULLIVAN,MICHAEL MD\nSigned: 06/19/2026 18:30"},
  ],
  consults:[
    {date:"Jun 19,26",stat:"dc",title:"ENDOCRINOLOGY CONSULT",num:"9705330",
     body:"Jun 19,26   (dc)  ENDOCRINOLOGY CONSULT  Cons #: 9705330\n\nTo Service:   ENDOCRINOLOGY\nDiagnosis:    New-onset DKA, age 45, no prior DM history\n\nASSESSMENT:\nDKA as initial manifestation of autoimmune (type 1) DM.\nGAD-65 Ab 148 IU/mL (ref <5). C-peptide 0.2 ng/mL.\n\nCRITICAL: This is TYPE 1 DM, not type 2.\n  DO NOT USE: Metformin, sulfonylureas, SGLT2 inhibitors\n  (SGLT2i increase DKA risk in T1DM -- CONTRAINDICATED)\n\nRECOMMENDATIONS:\n1. Glargine 20 units SC QHS.\n2. Lispro: 1:15 CHO ratio + ISF 1:50.\n3. Dexcom G7 CGM at discharge.\n4. Endocrinology f/u within 1 WEEK.\n5. Medic alert bracelet recommended.\n\n/es/ PATEL,TARIQ MD\nSigned: 06/19/2026 21:15\nStatus: COMPLETE"},
  ],
  labs:[
    {name:"DKA PANEL -- SERIAL BMP",cols:["06/19 Adm","06/19 +6h","06/19 +12h","06/20","Ref"],rows:[
      {t:"Glucose",v:["642","380","218","142","70-100"],f:["H","H","H","H"]},
      {t:"Sodium",v:["132","136","138","138","136-145"],f:["L","","",""]},
      {t:"Potassium",v:["3.2","3.6","3.9","4.1","3.5-5.0"],f:["L","","",""]},
      {t:"CO2",v:["8","14","18","22","22-29"],f:["L","L","L",""]},
      {t:"ANION GAP",v:["24","18","14","11","8-12"],f:["H","H","H",""]},
      {t:"Creatinine",v:["1.4","1.1","1.0","0.9","0.7-1.2"],f:["H","","",""]},
    ]},
    {name:"DIABETES WORKUP",cols:["Value","Reference"],rows:[
      {t:"HbA1c",v:["11.4%","<5.7% normal"],f:["H"]},
      {t:"GAD-65 Antibody",v:["POSITIVE 148 IU/mL ***","Negative <5 IU/mL"],f:["H"]},
      {t:"C-Peptide (fast)",v:["0.2 ng/mL ***","0.8-3.9 ng/mL"],f:["L"]},
      {t:"Triglycerides",v:["284 mg/dL","<150 mg/dL"],f:["H"]},
      {t:"TSH",v:["2.1 mIU/L","0.4-4.0 mIU/L"],f:[""]},
    ]},
    {name:"ABG (06/19 17:20)",cols:["Value","Reference"],rows:[
      {t:"pH",v:["7.18","7.35-7.45"],f:["L"]},
      {t:"PaCO2",v:["22 mmHg","35-45 mmHg"],f:["L"]},
      {t:"HCO3",v:["8 mEq/L","22-26 mEq/L"],f:["L"]},
      {t:"Base excess",v:["-18","-2 to +2"],f:["L"]},
    ]},
    {name:"URINALYSIS (06/19)",cols:["Result","Reference"],rows:[
      {t:"Glucose",v:["4+ (>1000 mg/dL)","Negative"],f:["H"]},
      {t:"Ketones",v:["LARGE","Negative"],f:["H"]},
      {t:"Protein",v:["Trace","Negative"],f:[""]},
    ]},
  ],
  vitals:[
    {dt:"06/20 06:00",t:"37.0",hr:"86",bp:"118/74",rr:"16",spo2:"98% RA",wt:"82",ht:"",pn:"0",pox:"98",qual:""},
    {dt:"06/19 23:00",t:"37.1",hr:"94",bp:"120/76",rr:"18",spo2:"98% RA",wt:"--",ht:"",pn:"0",pox:"98",qual:""},
    {dt:"06/19 17:10",t:"37.4",hr:"112 H",bp:"122/78",rr:"24 H",spo2:"97% RA",wt:"82",ht:"70 in",pn:"4",pox:"97",qual:""},
  ],
  io:[
    {dt:"06/20",po:"650",iv:"500",uo:"1400",net:"-250"},
    {dt:"06/19 (from 17:00)",po:"0 (NPO)",iv:"2500",uo:"1800",net:"+700 H"},
  ],
  imaging:[
    {date:"06/19/2026 17:30",name:"CHEST XRAY PA VIEW",stat:"Verified",examstat:"Complete",cnum:"2290",
     body:"CHEST X-RAY PA VIEW\nExam: JUN 19, 2026@17:30   Req: SULLIVAN,MICHAEL MD (ED)\nIndication: New DKA -- rule out precipitating infection.\n\nFINDINGS:\nLungs clear bilaterally. No consolidation, effusion, or\npneumothorax. Normal cardiac silhouette.\n\nIMPRESSION:\n1. NO ACUTE CARDIOPULMONARY ABNORMALITY.\n\n/ES/GREENBERG,ALAN MD"},
  ],
  orders:[
    {svc:"Lab",ord:"BMP Q6H WHILE ON INSULIN DRIP\n  Indication: DKA monitoring -- anion gap",start:"06/19/26 18:00",prov:"SULLIVAN,MICHAEL MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"GLUCOSE Q1H WHILE ON INSULIN DRIP",start:"06/19/26 18:00",prov:"SULLIVAN,MICHAEL MD",stat:"active",loc:"1no"},
    {svc:"Lab",ord:"HEMOGLOBIN A1C  New-onset DM workup",start:"06/19/26 18:10",prov:"SULLIVAN,MICHAEL MD",stat:"active",loc:"1no"},
    {svc:"Consult",ord:"ENDOCRINOLOGY CONSULT [COMPLETED]\n  Indication: New-onset DKA, possible T1DM",start:"06/19/26 18:30",prov:"SULLIVAN,MICHAEL MD",stat:"active",loc:"1no"},
  ],
  appointments:[
    {dt:"06/19/2026 17:10",loc:"4-West Inpatient (ED admit)",action:"Admitted"},
  ],
  immunizations:[
    {name:"COVID-19 (PFIZER) MRNA",reaction:"No reaction",dt:"Jan 05, 2024"},
  ],
},
};
